#!/usr/bin/env python

import re
import sys
import apastat
from signal import signal, SIGPIPE, SIG_DFL


__DEFAULT_URL = "http://localhost/server-status"


if __name__ == "__main__":
    # Use system default signal handling for handling SIG_PIPE
    # This means that pipeing apastat output will throw "Broken pipe" exception
    signal(SIGPIPE, SIG_DFL)

    order_by = ""

    all_workers = False
    if "-a" in sys.argv:
        all_workers = True

    if "-s" in sys.argv:
        order_by = "seconds_since"

    if "-c" in sys.argv:
        order_by = "client"

    if "--scoreboard-key" in sys.argv:
        print apastat.scoreboard_key

    else:
        # Is there 1 argument that's not prefixed with - ?
        args = [x for x in sys.argv[1:]  if not x.startswith("-")]

        if len(args) == 1:
            url = args[0]

            # Try to prefix URL with protocol
            if not re.match(r"^http(s)?://", url):
                url = "http://" + url
        else:
            url = __DEFAULT_URL

        apastat.run(url, all_workers=all_workers, order_by=order_by)
